# Generated by Django 2.2.7 on 2020-07-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_callback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callback',
            options={'verbose_name': 'Заявка на обратный звонок', 'verbose_name_plural': 'Заявки на обратный звонок'},
        ),
        migrations.AddField(
            model_name='callback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлено'),
        ),
        migrations.AddField(
            model_name='callback',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='Обработана ?'),
        ),
        migrations.AddField(
            model_name='callback',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо '),
        ),
        migrations.AddField(
            model_name='callback',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон '),
        ),
        migrations.AddField(
            model_name='callback',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время '),
        ),
    ]
