# Generated by Django 2.2.7 on 2020-07-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200702_1048'),
        ('pages', '0003_auto_20200702_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='callback',
            name='ads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Ads', verbose_name='По поводу'),
        ),
    ]
