# Generated by Django 2.2.7 on 2020-06-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200629_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='ads_type',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='action_type',
            field=models.CharField(choices=[('TR', 'Сдать'), ('SL', 'Продать'), ('BY', 'Купить'), ('RT', 'Снять')], default='TR', max_length=2, verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='currency_type',
            field=models.CharField(choices=[('RU', 'Рубли'), ('US', 'Доллары')], default='RU', max_length=2, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='house_type',
            field=models.CharField(blank=True, choices=[('BR', 'Кирпич'), ('MN', 'Монолит'), ('PL', 'Панель')], max_length=2, null=True, verbose_name='Тип постройки'),
        ),
    ]
