# Generated by Django 2.2.7 on 2020-06-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200627_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Метро')),
                ('name_slug', models.CharField(blank=True, editable=False, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='ads',
            name='merto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Metro', verbose_name='Метро'),
        ),
    ]
