# Generated by Django 2.2.7 on 2020-07-02 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_auto_20200701_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='show_total_square',
            field=models.BooleanField(default=True, verbose_name='Показывать общую площадь  в форме на главной?'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='ads_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Объявления с сайта'),
        ),
        migrations.AlterField(
            model_name='adsimage',
            name='ads',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ads.Ads', verbose_name='Для обьявления'),
        ),
    ]
