# Generated by Django 2.2.7 on 2020-06-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200627_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='cadaster_numbet',
            new_name='cadaster_number',
        ),
    ]
