# Generated by Django 2.2.7 on 2020-06-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_auto_20200630_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='ads_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
