# Generated by Django 2.2.7 on 2020-06-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_auto_20200627_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='currency_type',
            field=models.CharField(choices=[('RU', 'Рубли'), ('US', 'Доллары')], default='RU', max_length=2, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='ads',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
