# Generated by Django 2.1.4 on 2020-07-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_ads_is_living'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='feed_category',
            field=models.CharField(choices=[('TR', 'Сдать'), ('SL', 'Продать'), ('BY', 'Купить'), ('RT', 'Снять')], default='F1', max_length=20, verbose_name='Категория объекта (Для фида)'),
        ),
    ]
