# Generated by Django 2.2.7 on 2020-06-27 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_auto_20200627_1225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metro',
            options={'verbose_name': 'Метро', 'verbose_name_plural': 'Метро'},
        ),
        migrations.RemoveField(
            model_name='ads',
            name='merto',
        ),
        migrations.AddField(
            model_name='ads',
            name='metro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ads.Metro', verbose_name='Метро'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='number',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Номер объекта'),
        ),
    ]
