# Generated by Django 2.2.7 on 2020-06-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_auto_20200627_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsimage',
            name='image_full',
        ),
        migrations.AddField(
            model_name='adsimage',
            name='image',
            field=models.ImageField(null=True, upload_to='ads/image', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='adsimage',
            name='image_main',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ads/image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='balkon_type',
            field=models.CharField(blank=True, choices=[('B', 'Балкон'), ('L', 'Лоджия'), ('BB', '2 балкона'), ('L', '2 лоджии')], max_length=2, null=True, verbose_name='Балкон'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='rooms',
            field=models.CharField(blank=True, choices=[('R1', '1'), ('R2', '2'), ('R3', '3'), ('R4', '4'), ('R5', '5+')], max_length=2, null=True, verbose_name='Комнат'),
        ),
        migrations.AlterField(
            model_name='adsimage',
            name='image_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='ads/image', verbose_name='Изображение'),
        ),
    ]
