# Generated by Django 2.1.4 on 2020-07-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0006_ads_feed_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='built_year',
            field=models.CharField(max_length=255, null=True, verbose_name='Год сдачи (Для фида)'),
        ),
    ]
