# Generated by Django 2.1.4 on 2020-07-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0007_ads_built_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='feed_deal_status',
            field=models.CharField(choices=[('S1', 'первичная продажа'), ('S2', 'продажа от застройщика'), ('S3', 'переуступка'), ('S4', 'прямая продажа'), ('S5', 'первичная продажа вторички'), ('S6', 'встречная продажа')], default='S1', max_length=20, verbose_name='Тип сделки (Для фида)'),
        ),
        migrations.AlterField(
            model_name='ads',
            name='feed_category',
            field=models.CharField(choices=[('F1', 'дача'), ('F2', 'коттедж'), ('F3', 'дом'), ('F4', 'дом с участком'), ('F5', 'участок'), ('F6', 'часть дома'), ('F7', 'квартира'), ('F8', 'комната'), ('F9', 'таунхаус'), ('F10', 'дуплекс'), ('F11', 'гараж')], default='F1', max_length=20, verbose_name='Категория объекта (Для фида)'),
        ),
    ]
