# Generated by Django 2.1.4 on 2020-07-31 00:39

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_auto_20200723_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsimage',
            name='image',
            field=models.ImageField(null=True, upload_to=ads.models.path_and_rename, verbose_name='Изображение'),
        ),
    ]
