# Generated by Django 2.1.4 on 2020-07-01 06:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Название статьи')),
                ('name_slug', models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/', verbose_name='Изображение превью 200x200)')),
                ('page_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тэг Title')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='Тэг Description')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='Статья.')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Отображать статью ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
