# Generated by Django 2.2.7 on 2020-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='similar',
        ),
        migrations.AlterField(
            model_name='article',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Отображать статью ?'),
        ),
    ]
