# Generated by Django 2.1.4 on 2020-07-31 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='article/', verbose_name='Изображение превью 200x200)'),
        ),
    ]
